mod:
  Auth:
    messages:
      BadLogin                          : Either there is no user with that name or you have used an incorrect password.
      Connect                           : |
                                            Welcome to jasmine.

                                            Type "login <name> <password>" to authenticate as a user.
      Connected                         : Connected as {name}.
      Disconnected                      : Good bye!
