port                                    : 7445
mudname                                 : jasmine
log:
  file                                  : log/jasmine.log
timeout:
  connect                               : 300
  idle                                  : -1
