port                                    : 4201
mudname                                 : NodeMud
log                                     : log/NodeMud.log
timeout:
  connect                               : 300
  idle                                  : -1
