port                                    : 4201
mudname                                 : NodeMud
log:
  file                                  : log/NodeMud.log
timeout:
  connect                               : 300
  idle                                  : -1
